name: Build Flutter APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Extract Zip File
        run: |
          mkdir -p extracted_app
          unzip -o "*.zip" -d extracted_app

      - name: Build APK
        run: |
          PUB_DIR=$(find extracted_app -name "pubspec.yaml" -exec dirname {} \; | head -n 1)
          cd "$PUB_DIR"
          flutter pub get
          flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: extracted_app/**/build/app/outputs/flutter-apk/app-release.apk
